### ISSUE TITLE
Fix the slow database using drag and drop

### ISSUE THREAD

**Issue by PHPirates** [PHPirates/plep#36]
the label changelistener to which you drag is fired four times, so updates database four times while it shouldn't update database as that is already handles in ondragdropped, same for the label listener from which you drag one time.

**Comment by slideclimb** [comment]
ComboBox index resets to -1 every time, same for value resetting to null. So when you drag something, all the ComboBox's get reminded of their actual selected index and value, and therefore trigger the valueChangedListener. Causing every Cell to update its day.
